### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by Srokap** [stewarttylerr/ftpserver#3]
There are several issues when running `npm test` it seems. From what I can tell, we at least have problem with:
- [ ] Tests depending on system having directory `/home/tyler/Documents` with some existing structure in it.
- [ ] ESLint default configuraton failing a lot on current code base. (having .eslintrc.json would be nice to avoid depending on some gulp defaults)

See https://travis-ci.org/Srokap/ftpserver as example of runinng it on TravisCI. If we were able to add local ftp files to repo and reference form tests we might integrate it on Travis in main repo. How about that?

**Comment by stewarttylerr** [comment]
@Srokap Thank you, I'll update the tests and add my .eslintrc

**Comment by stewarttylerr** [comment]
@Srokap How do these changes look? https://github.com/stewarttylerr/ftpserver/pull/4
