### ISSUE TITLE
STOR command receives filename split by spaces 

### ISSUE THREAD

**Issue by crash83k** [stewarttylerr/ftpserver#6]
I know you're not splitting the filename by space, but when the file name comes into the STOR command, the filename pieces are passed as parts of the argument instead.

So the args object looks like this when you attempt to upload "Death Metal Batman2.mp4":
`{ '0': 'STOR', '1': '/Death', '2': 'Metal', '3': 'Batman2.mp4' }` 

I'm thinking for the STOR command, it may be good to join the arguments (excluding the '0' index) with a space. Either that, or we should have a way to do some sort of pre-processing for each command as an option before the data is passed into the command module.

**Comment by stewarttylerr** [comment]
@crash83k How about if we made it so you had to wrap the path in quotes? `STOR "/death meta/batman.mp4"`

**Comment by crash83k** [comment]
How would I enforce that on an FTP client?

**Comment by stewarttylerr** [comment]
@crash83k Great point!
Something like https://github.com/stewarttylerr/ftpserver/pull/7 would probably be our best bet then

**Comment by crash83k** [comment]
Sounds good. I'm doing this already on my end and it's working perfectly.

**Comment by stewarttylerr** [comment]
https://github.com/stewarttylerr/ftpserver/pull/10
